### ISSUE TITLE
[DarkDarkTheme] Cut Off Discord Icon

### ISSUE THREAD

**Issue by underscore11-wh** [KyzaGitHub/Khub#29]
**What theme does the bug occur in?**
DarkDarkTheme

**What version is the plugin?**
v3.0.10

**Describe the bug.**
Discord Icon in top left is cut off and shifted to the side.

**Give steps to reproduce the bug.**
1. Enable theme
2. Look at discord Icon

**Add attachments or screenshots to help me reproduce the bug.**
![image](https://user-images.githubusercontent.com/55677189/65627201-b4e30f00-df83-11e9-810f-00e29a227a74.png)

**Comment by KyzaGitHub** [comment]
It seems that this was a problem with Discord. I noticed it myself, didn't do anything, and now it is fixed.

**Comment by underscore11-wh** [comment]
Not resolved. I've disabled everything but DDT and Zlib, reloaded 2 times, updated DDT, still borked.
![image](https://user-images.githubusercontent.com/55677189/65717984-6f901180-e057-11e9-98a8-9bd2de447018.png)

**Comment by KyzaGitHub** [comment]
Alright, I'll look into it further.

**Comment by KyzaGitHub** [comment]
Have you tried redownloading KSSLibrary?

**Comment by underscore11-wh** [comment]
Downloaded latest KSS (0.0.7), and now the theme isn't loading at all.
```Uncaught (in promise) TypeError: Cannot read property 'split' of undefined
    at new Selector (C:\Users\NAME\AppData\Roaming\BetterDiscord\plugins\0PluginLibrary.plugin.js:5941:33)
    at new KSSLibrary (C:\Users\NAME\AppData\Roaming\BetterDiscord\plugins\1KSSLibrary.plugin.js:95:18)
    at DarkDarkTheme.onStart (C:\Users\NAME\AppData\Roaming\BetterDiscord\plugins\DarkDarkTheme.plugin.js:217:21)
    at DarkDarkTheme.start (C:\Users\NAME\AppData\Roaming\BetterDiscord\plugins\0PluginLibrary.plugin.js:6208:58)
    at PluginModule.loadPlugins (https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/45916aef50206a8fd7613224cc5d7e52d9f3ef0e/js/main.min.js:55:23901)
    at Core.init (https://cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/45916aef50206a8fd7613224cc5d7e52d9f3ef0e/js/main.min.js:4:683)```

Also seems like KSS's auto-updater isn't working, since this is the second or third time I've had to manually redownload.

**Comment by KyzaGitHub** [comment]
These are both solved in the latest CSS update. Just reload the plugin and it should be applied.
